plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'hufsbus.com'
version = '0.0.1-SNAPSHOT'
description = 'be'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // Spring boot 기본
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // interact db with jpa
//    implementation 'org.springframework.boot:spring-boot-starter-security' // security filter chain on springboot application
    implementation 'org.springframework.boot:spring-boot-starter-validation' // dto validation check
    implementation 'org.springframework.boot:spring-boot-starter-web' // default dependency - json convert jackson, inner tomcat, spring mvc, restcontroller, httpmethod mapper
    compileOnly 'org.projectlombok:lombok' // lombok annotation
    annotationProcessor 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // db
    runtimeOnly 'com.mysql:mysql-connector-j'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // JSON 파싱을 위해 필요

    // excel
    implementation 'org.apache.poi:poi:5.4.0'
    implementation 'org.apache.poi:poi-ooxml:5.4.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
